### ISSUE TITLE
Potential NPE in estimateSmartFee

### ISSUE THREAD

**Issue by tdiesler** [Polve/JavaBitcoindRpcClient#82]
```
java.lang.NullPointerException
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at wf.bitcoin.javabitcoindrpcclient.MapWrapper.mapBigDecimal(MapWrapper.java:74)
	at wf.bitcoin.javabitcoindrpcclient.MapWrapper.mapBigDecimal(MapWrapper.java:60)
	at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient$SmartFeeResultMapWrapper.feeRate(BitcoinJSONRPCClient.java:925)
	at io.nessus.bitcoin.BitcoinNetwork.estimateSmartFee(BitcoinNetwork.java:42)
	at io.nessus.AbstractWallet.sendToAddress(AbstractWallet.java:246)
	at io.nessus.AbstractWallet.sendFromLabel(AbstractWallet.java:235)
	at io.nessus.test.bitcoin.RawTxTest.after(RawTxTest.java:62)
```

**Comment by Polve** [comment]
What do you propose to do in case feerate is not present?
